name: Test Pre-Release action

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Runs on Pre-Release
      run: echo "This is a Pre-Release"